"""add blocklist_entries table

Revision ID: b10019d02675
Revises: 19b509ab3ea2
Create Date: 2026-07-07 22:37:43.716605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10019d02675'
down_revision: Union[str, Sequence[str], None] = '19b509ab3ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocklist_entries_id'), 'blocklist_entries', ['id'], unique=False)
    op.create_index(op.f('ix_blocklist_entries_url'), 'blocklist_entries', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocklist_entries_url'), table_name='blocklist_entries')
    op.drop_index(op.f('ix_blocklist_entries_id'), table_name='blocklist_entries')
    op.drop_table('blocklist_entries')
    # ### end Alembic commands ###
